services:
  shawnaustinrocks:
    build: .
    container_name: shawnaustinrocks
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=shawnaustinrocks.com,www.shawnaustinrocks.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=shawnaustinrocks.com,www.shawnaustinrocks.com
      - LETSENCRYPT_EMAIL=robert.mccaleb@gmail.com
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
